### ISSUE TITLE
Support required Vite@5  

### ISSUE THREAD

**Issue by YangFong** [yuyinws/vite-plugin-turbo-console#11]
Hi, recently Vite was updated to 5 and seems no longer compatible.

![image](https://github.com/yuyinws/vite-plugin-turbo-console/assets/70502828/a97fc829-623d-4226-a3e4-3313a36ab9aa)

https://github.com/yuyinws/vite-plugin-turbo-console/blob/a9f28d0a07ed82e8d66793358a2eada655592433/src/index.ts#L55

**Comment by yuyinws** [comment]
`V0.3.0` is compatible with vite@5 now.
