### ISSUE TITLE
ReferenceError: __dirname is not defined in ES module scope

### ISSUE THREAD

**Issue by danestves** [yuyinws/vite-plugin-turbo-console#5]
Using `"type": "module"` I'm getting this error

![](https://github.com/yuyinws/vite-plugin-turbo-console/assets/31737273/06649e55-8a6a-4167-93dc-12b9a1223aad)

**Comment by yuyinws** [comment]
Thanks for your report. Please update to [0.2.1](https://github.com/yuyinws/vite-plugin-turbo-console/releases/tag/v0.2.1). It should be fixed.
